[package]
name = "quote-builder-macros"
version = "0.1.0"
authors = ["Chip Reed <chip@chip.sh>"]
edition = "2018"
license = "Apache-2.0 or MIT"

[lib]
proc-macro = true

[dependencies]
quote-builder-impl = { path = "../quote-builder-impl", version = "0.1" }