[package]
name = "quote-builder-impl"
version = "0.1.0"
authors = ["Chip Reed <chip@chip.sh>"]
edition = "2018"
license = "Apache-2.0 or MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
