name: ci
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "crates/**"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10


jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    env:
      CC: deny_c

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72

    - name: Formatting
      run: cargo fmt --all -- --check

    - name: Compile
      run: cargo test --no-run
      
    - name: Clippy
      run: cargo clippy

    - name: Test
      run: cargo test -- --nocapture --quiet